nAgents: 10000
nSteps: 1000000
nSaveSteps: 1
nRuns: 10
networkP: 0.8
networkM: 10
additionalLinksFraction: 0.01
virtualLayer: true
epidemicLayer: true
comorbidities: false
qVoterParameters:
  p: 0.2
  q: 6
epidemicLayerParameters:
  beta: 0.1
  zeta: 0.5 # attitude towards vaccination
  alpha: 0.9 # effectiveness of the vaccination
  gamma: 0.5
  mu: 0.9
  kappa: 0.1
maxInfectedTimeMean: 10
maxInfectedTimeStd: 5
positiveOpinionFraction: 0.1
proPisFraction: 0.45
pisVaccinationCorrelation: 0.3 # assumption: negative
infectedFraction: 0.1
fractionIllnessA: 0.0
fractionIllnessB: 0.0
outputFolder: simulations/example_config_model_2
firstParameterRange:
  start: 0.0
  end: 1.0
  count: 11
  vals: null
  type: pisProFraction
secondParameterRange: null
thirdParameterRange: null
linksRemoval: false
nQVoterPerStep: 1
vaccinationFraction: 0.0
neglectNeighboursPiS: false