nAgents: 10000
nSteps: 2000000
nSaveSteps: 1000
nRuns: 1
networkP: 0.0
networkM: 3
additionalLinksFraction: 0.01
virtualLayer: true
epidemicLayer: true
comorbidities: true
qVoterParameters:
  p: 1.0
  q: 3
epidemicLayerParameters:
  beta: 0.5
  gamma: 0.3
  mu: 0.9
  kappa: 0.1
maxInfectedTimeMean: 10
maxInfectedTimeStd: 5
positiveOpinionFraction: 1.0
infectedFraction: 0.1
fractionIllnessA: 0.0
fractionIllnessB: 0.0
outputFolder: simulations/test
firstParameterRange:
  start: 0.01
  end: 0.99
  count: 10
  type: p