nAgents: 10000
nSteps: 100
nSaveSteps: 1
nRuns: 10
networkP: 0.8
networkM: 10
additionalLinksFraction: 0.01
virtualLayer: true
epidemicLayer: true
comorbidities: false
qVoterParameters:
  p: 0.2
  q: 6
epidemicLayerParameters:
  beta: 0.1
  zeta: 0.0
  alpha: 0.0
  gamma: 0.5
  mu: 0.9
  kappa: 0.1
maxInfectedTimeMean: 10
maxInfectedTimeStd: 5
positiveOpinionFraction: 1.0 # all agents +1
proPisFraction: 0.0
pisVaccinationCorrelation: 0.0
infectedFraction: 0.1
fractionIllnessA: 0.0
fractionIllnessB: 0.0
outputFolder: simulations/max_infection_peak_vs_beta_low_beta_nruns_10
firstParameterRange:
  start: 0.0
  end: 0.5
  count: 51
  vals: null
  type: beta
secondParameterRange:
  start: 0
  end: 0
  count: 0
  vals: [1000, 10000, 30000]
  type: N
thirdParameterRange: null
#  start: 0
#  end: 0
#  count: 0
#  vals: [0.01, 0.05, 0.1, 0.3, 0.5]
#  type: p
linksRemoval: false
nQVoterPerStep: 1
vaccinationFraction: 0.0
neglectNeighboursPiS: false
