nAgents: 10000
nSteps: 1000000
nSaveSteps: 1000
nRuns: 10
networkP: 0.8
networkM: 10
additionalLinksFraction: 0.01
virtualLayer: true
epidemicLayer: true
comorbidities: false
qVoterParameters:
  p: 0.01
  q: 6
epidemicLayerParameters:
  beta: 0.9
  gamma: 0.5
  mu: 0.9
  kappa: 0.1
maxInfectedTimeMean: 10
maxInfectedTimeStd: 5
positiveOpinionFraction: 1.0
infectedFraction: 0.1
fractionIllnessA: 0.0
fractionIllnessB: 0.0
proPisFraction: 0.0 # do not use this!
pisVaccinationCorrelation: 0.0
outputFolder: simulations/results_remove_links_parameters_beta_range_small_p_different_dynamics_all
firstParameterRange:
  start: 0.0
  end: 1.0
  count: 51
  vals: null
  type: positiveOpinionFraction
secondParameterRange:
  start: 0.0
  end: 1.0
  count: 21
  vals: [0.01, 0.02, 0.05, 0.1, 0.5]
  type: beta
thirdParameterRange:
  start: 0.0
  end: 0.0
  count: 0
  vals: [1, 2, 5, 10, 20]
  type: nQVoterPerStep
linksRemoval: false
nQVoterPerStep: 1
