# Check if epidemic layer is working
nAgents: 10000
nSteps: 400000
nSaveSteps: 500
nRuns: 1
networkP: 0.0
networkM: 3
additionalLinksFraction: 0.01
virtualLayer: false
epidemicLayer: true
comorbidities: false
qVoterParameters:
  p: 1.0
  q: 5
epidemicLayerParameters:
  beta: 0.5
  gamma: 0.3
  mu: 0.9
  kappa: 0.1
  maxInfectedTime: 10
positiveOpinionFraction: 1.0
infectedFraction: 0.1
fractionIllnessA: 0.0
fractionIllnessB: 0.0
outputFolder: simulations/test_epidemic_layer
firstParameterRange:
  start: 0.0
  end: 1.0
  count: 10
  type: beta
