nAgents: 10000
nSteps: 1000000
nSaveSteps: 50000
nRuns: 5
networkP: 0.8
networkM: 10
additionalLinksFraction: 0.01
virtualLayer: true
epidemicLayer: true
comorbidities: false
qVoterParameters:
  p: 1.0
  q: 6
epidemicLayerParameters:
  beta: 0.1
  gamma: 0.5
  mu: 0.8
  kappa: 0.2
maxInfectedTimeMean: 10
maxInfectedTimeStd: 5
positiveOpinionFraction: 1.0
infectedFraction: 0.1
fractionIllnessA: 0.0
fractionIllnessB: 0.0
outputFolder: simulations/test_removal_links_on_phase_transition_low_beta
firstParameterRange:
  start: 0.0
  end: 0.3
  count: 50
  vals: null
  type: p
secondParameterRange: null
linksRemoval: true
nQVoterPerStep: 1