# Check if q-voter model works
# Test the relation between p and mean opinion at the end of the simulations
nAgents: 10000
nSteps: 1000000
nSaveSteps: 1000
nRuns: 10
networkP: 0.0
networkM: 20
additionalLinksFraction: 0.0
virtualLayer: true
epidemicLayer: false
comorbidities: false
qVoterParameters:
  p: 0.1
  q: 8
epidemicLayerParameters:
  beta: 0.5
  gamma: 0.3
  mu: 0.9
  kappa: 0.1
maxInfectedTimeMean: 10
maxInfectedTimeStd: 10
positiveOpinionFraction: 0.1
infectedFraction: 0.1
fractionIllnessA: 0.0
fractionIllnessB: 0.0
outputFolder: simulations/test_q_voter_new_shuffle
firstParameterRange:
  start: 0.0
  end: 1.0
  count: 11
  type: positiveOpinionFraction